- name: Upload via SFTP
  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
  with:
    server: dev.screencraft.net.au
    port: 22
    username: ${{ secrets.SFTP_USERNAME }}
    password: ${{ secrets.SFTP_PASSWORD }}   # or use ssh_private_key
    local_path: ./
    remote_path: /a/reyesmar/
    exclude: ".git*,node_modules/**,.github/**"
