- name: Upload files via FTPS (explicit 21)
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: dev.screencraft.net.au
    protocol: ftps
    port: 21
    security: loose       # ðŸ‘ˆ add this
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    local-dir: ./
    server-dir: /a/reyesmar/
    exclude: |
      **/.git*
      **/node_modules/**
      **/.github/**
